# Config for https://github.com/apps/release-drafter
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
sort-direction: ascending
template: |
  $CHANGES
  ## New Features
  ## Bug Fixes
  ## Refactoring
  ## Deployment
  ## Documentation
  ## Bump dependencies version
  powered by @dependabot
  |package|old|new|PR(s)|
  |-------|---|---|-----|
  |||||
