name: 'Post LGTM Image'
description: 'Post image if you comment "LGTM"'
author: 'ddradar'
inputs:
  token:
    description: 'Your GitHub Token (provided by Actions)'
    required: true
  image-url:
    description: 'Image URL path'
    required: true
  search-pattern:
    description: 'Regexp pattern this action reacts'
    required: false
    default: ^(lgtm|LGTM)$
branding:
  icon: 'thumbs-up'
  color: 'purple'
runs:
  using: 'node12'
  main: 'dist/index.js'
