name: 'Post LGTM Image'
description: 'Post image if you comment "LGTM"'
author: 'ddradar'
inputs:
  token:
    description: >
      GitHub Access Token to create issue comment.
      In many cases, you do not need to prepare yourself. (provided by GitHub Actions)
      Token must have issues:write permission.
    default: ${{ github.token }}
  image-url:
    description: 'Image URL path'
    required: true
  search-pattern:
    description: 'Regexp pattern this action reacts'
    default: ^(lgtm|LGTM)$
branding:
  icon: 'thumbs-up'
  color: 'purple'
runs:
  using: 'node12'
  main: 'dist/index.js'
